"""
Alpaca paper trading executor for volatility-targeted ETF positions.

Reads tomorrow_positions.csv generated by the daily forecast pipeline
and executes orders on an Alpaca paper trading account.  Each order
(or no-op) is appended to artifacts/signals/<DATE>/orders.csv.

Required environment variables:
    ALPACA_API_KEY    — Alpaca API key ID
    ALPACA_SECRET_KEY — Alpaca secret key

Usage:
    python alpaca_executor.py --ticker SPY
    python alpaca_executor.py --ticker QQQ --date 2026-04-10
    python alpaca_executor.py --ticker IWM --dry-run
"""

from __future__ import annotations

import argparse
import csv
import logging
import os
import sys
from datetime import date, datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Path setup — allow running from project root
# ---------------------------------------------------------------------------
_project_root = Path(__file__).resolve().parent
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))
if str(_project_root / "src") not in sys.path:
    sys.path.insert(0, str(_project_root / "src"))

import volatility_paths as vpaths  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
ALLOWED_TICKERS = {"SPY", "QQQ", "IWM"}
# Hard cap: dollar_exposure from the signal must not exceed this amount.
# Keeps a $500 paper account from accidentally over-exposing.
MAX_DOLLAR_EXPOSURE = 500.0

LOG_FIELDNAMES = [
    "timestamp",
    "ticker",
    "action",
    "shares",
    "side",
    "order_id",
    "status",
    "dollar_exposure",
    "forecast_vol_ann",
    "target_vol_ann",
    "exposure_multiplier",
    "error",
]

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Signal reader
# ---------------------------------------------------------------------------
def read_position_signal(ticker: str, date_str: str) -> dict | None:
    """
    Read tomorrow_positions.csv for *ticker* on *date_str*.

    Returns the matching row as a dict, or None if not found.
    Does NOT raise — caller decides how to handle a missing signal.
    """
    positions_file = vpaths.SIGNALS_DIR / date_str / "tomorrow_positions.csv"

    if not positions_file.exists():
        log.error("Positions file not found: %s", positions_file)
        log.error("Run 'python volforecast_cli.py daily --ticker %s --export' first.", ticker)
        return None

    with open(positions_file, newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            if row.get("ticker", "").upper() == ticker:
                return row

    log.warning("No signal for ticker %r in %s", ticker, positions_file)
    return None


# ---------------------------------------------------------------------------
# Order log
# ---------------------------------------------------------------------------
def append_order_log(date_str: str, record: dict) -> None:
    """Append one row to artifacts/signals/<date_str>/orders.csv."""
    orders_path = vpaths.get_signals_dir(date_str) / "orders.csv"
    write_header = not orders_path.exists()

    with open(orders_path, "a", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=LOG_FIELDNAMES, extrasaction="ignore")
        if write_header:
            writer.writeheader()
        writer.writerow(record)

    log.info("Order logged → %s", orders_path)


# ---------------------------------------------------------------------------
# Trade execution
# ---------------------------------------------------------------------------
def execute_trade(signal: dict, dry_run: bool = False) -> dict:
    """
    Reconcile desired vs current Alpaca position and submit a market order.

    Args:
        signal:  Row dict from tomorrow_positions.csv.
        dry_run: If True, log what would happen but do not call the API.

    Returns:
        A dict matching LOG_FIELDNAMES for appending to orders.csv.
    """
    # Lazy import so the rest of the module works without alpaca-py installed
    from alpaca.trading.client import TradingClient
    from alpaca.trading.enums import OrderSide, TimeInForce
    from alpaca.trading.requests import MarketOrderRequest

    api_key = os.environ.get("ALPACA_API_KEY", "")
    secret_key = os.environ.get("ALPACA_SECRET_KEY", "")
    if not api_key or not secret_key:
        raise EnvironmentError(
            "ALPACA_API_KEY and ALPACA_SECRET_KEY must be set as environment variables."
        )

    ticker = signal["ticker"].upper()
    desired_shares = int(signal["desired_shares_int"])
    dollar_exposure = float(signal["dollar_exposure"])
    forecast_vol = float(signal["forecast_vol_ann"])
    target_vol = float(signal["target_vol_ann"])
    exp_mult = float(signal["exposure_multiplier"])

    # Safety guard — clamp if signal somehow exceeds the account cap
    if dollar_exposure > MAX_DOLLAR_EXPOSURE:
        log.warning(
            "Signal dollar_exposure $%.2f exceeds account cap $%.2f — setting desired_shares=0.",
            dollar_exposure,
            MAX_DOLLAR_EXPOSURE,
        )
        desired_shares = 0

    client = TradingClient(api_key, secret_key, paper=True)

    # Get current shares held for this ticker (0 if no open position)
    current_shares = 0
    try:
        position = client.get_open_position(ticker)
        current_shares = int(float(position.qty))
    except Exception:
        # API raises an error (not a library exception) when no position exists
        current_shares = 0

    delta = desired_shares - current_shares
    log.info(
        "%s — desired=%d  current=%d  delta=%+d",
        ticker, desired_shares, current_shares, delta,
    )

    record: dict = {
        "timestamp": datetime.utcnow().isoformat(),
        "ticker": ticker,
        "action": "no_change",
        "shares": 0,
        "side": "",
        "order_id": "",
        "status": "skipped",
        "dollar_exposure": dollar_exposure,
        "forecast_vol_ann": forecast_vol,
        "target_vol_ann": target_vol,
        "exposure_multiplier": exp_mult,
        "error": "",
    }

    if delta == 0:
        log.info("%s: position already at target — no order needed.", ticker)
        return record

    side = OrderSide.BUY if delta > 0 else OrderSide.SELL
    qty = abs(delta)
    record.update({"action": "order", "shares": qty, "side": side.value})

    if dry_run:
        log.info("[DRY RUN] Would %s %d share(s) of %s.", side.value, qty, ticker)
        record["status"] = "dry_run"
        return record

    try:
        order_req = MarketOrderRequest(
            symbol=ticker,
            qty=qty,
            side=side,
            # DAY orders placed after hours queue for next market open — ideal
            # for signals generated after the 4 PM ET close.
            time_in_force=TimeInForce.DAY,
        )
        order = client.submit_order(order_req)
        record["order_id"] = str(order.id)
        record["status"] = str(order.status)
        log.info(
            "Order submitted — %s %d %s | id=%s status=%s",
            side.value, qty, ticker, order.id, order.status,
        )
    except Exception as exc:
        record["status"] = "error"
        record["error"] = str(exc)
        log.error("Order submission failed for %s: %s", ticker, exc)
        # Do NOT re-raise — caller logs the record and exits cleanly.

    return record


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(
        description="Execute Alpaca paper trades from the daily vol-forecast signal."
    )
    parser.add_argument(
        "--ticker",
        required=True,
        help="ETF ticker to trade. Must be one of: SPY, QQQ, IWM.",
    )
    parser.add_argument(
        "--date",
        default=None,
        metavar="YYYY-MM-DD",
        help="Signal date to read (default: today).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be traded without submitting orders.",
    )
    args = parser.parse_args()

    ticker = args.ticker.upper()
    date_str = args.date or date.today().isoformat()

    log.info(
        "=== Alpaca executor | ticker=%s  date=%s  dry_run=%s ===",
        ticker, date_str, args.dry_run,
    )

    # Enforce ETF-only constraint
    if ticker not in ALLOWED_TICKERS:
        log.error(
            "Ticker %r is not in the allowed list %s. Only ETFs are permitted.",
            ticker, sorted(ALLOWED_TICKERS),
        )
        return 1

    # Read signal
    signal = read_position_signal(ticker, date_str)
    if signal is None:
        log.error("No position signal found — exiting without trading.")
        return 1

    log.info(
        "Signal — shares=%s  dollar_exposure=%s  forecast_vol=%.4f",
        signal.get("desired_shares_int"),
        signal.get("dollar_exposure"),
        float(signal.get("forecast_vol_ann", 0)),
    )

    # Execute (or dry-run) the trade
    record: dict
    try:
        record = execute_trade(signal, dry_run=args.dry_run)
    except EnvironmentError as exc:
        log.error("%s", exc)
        return 1
    except Exception as exc:
        log.error("Unexpected error during trade execution: %s", exc, exc_info=True)
        record = {
            "timestamp": datetime.utcnow().isoformat(),
            "ticker": ticker,
            "action": "error",
            "shares": 0,
            "side": "",
            "order_id": "",
            "status": "error",
            "dollar_exposure": 0,
            "forecast_vol_ann": 0,
            "target_vol_ann": 0,
            "exposure_multiplier": 0,
            "error": str(exc),
        }

    # Always write an order log entry — even for no-ops and errors
    try:
        append_order_log(date_str, record)
    except Exception as exc:
        log.error("Failed to write order log: %s", exc)

    # Return non-zero only on hard errors that prevent any trade attempt
    return 0 if record.get("status") not in ("error",) else 1


if __name__ == "__main__":
    sys.exit(main())
